version: '3'

services:
  loki:
    image: grafana/loki:2.7.2
    container_name: loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    volumes:
      - ./loki-config:/etc/loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:9.6.3
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Puedes cambiar la contraseña
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
